color:
  saturation: 0.7363051
  brandStrength: 0.9027927
  rhythmicContrast: 0.3646616
  brandColors:
    - '#F6F6F6'
    - '#050105'
    - '#5A4C4C'
  lightness: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0
typography_spectrum: 0.9414608
name: '๏lYnn:waldr◎p๏f◎T◎๏'
