collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9414608
color:
  saturation: 0
  brandStrength: 0.9027927
  lightness: 1
  brandColors:
    - '#F6F6F6'
    - '#050105'
    - '#5A4C4C'
  rhythmicContrast: 0
layout_spectrum: 0.8501611
name: '๏lYnn:waldr◎p๏f◎T◎๏'
