layout_spectrum: 0.5601504
typography_spectrum: 0.9414608
color:
  saturation: 0
  lightness: 0
  brandStrength: 0.9027927
  brandColors:
    - '#F6F6F6'
    - '#050105'
    - '#5A4C4C'
  rhythmicContrast: 0
name: '๏lYnn:waldr◎p:f◎t◎๏'
