collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.9414608
color:
  saturation: 0.7363051
  brandStrength: 0.9027927
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#0E060B'
    - '#5A4C4C'
  rhythmicContrast: 0.3646616
layout_spectrum: 0.4291085
name: '๏lYnn:waldr◎p๏f◎T◎๏'
